include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    - avoid_dynamic_calls
    - avoid_empty_else
    - cancel_subscriptions
    - close_sinks
    - literal_only_boolean_expressions
    - no_duplicate_case_values
    - prefer_void_to_null
    - require_trailing_commas
    - unawaited_futures
    - unnecessary_await_in_return
    - use_key_in_widget_constructors
    - use_late_for_private_fields_and_variables
    - use_super_parameters
